### ISSUE TITLE
Release to NPM

### ISSUE THREAD

**Issue by schrapel** [abhisekp/yup-phone#115]
@abhisekp Are you able to release this package to NPM so we can use it? :) Thanks for the cool package.

**Comment by abhisekp** [comment]
@schrapel You can install it using `npm install abhisekp/yup-phone`.

**Comment by glennwidener** [comment]
npm install per above fails:
> mpn-on@0.3.3 postinstall C:\Users\glenn.widener\src\vision-fe\node_modules\mpn-on
> ./install

'.' is not recognized as an internal or external command,
operable program or batch file.
----
"mpn" sure looks like a typo!

**Comment by abhisekp** [comment]
@glennwidener I guess this is `npm` specific problem. This is that package http://npm.im/mpn-on

Try using `yarn` maybe?

**Comment by dspacejs** [comment]
The README install instructions for NPM should be updated to: `npm install --save abhisekp/yup-phone`

**Comment by abhisekp** [comment]
@dspacejs would you be interested to make your first PR in this project?

**Comment by abhisekp** [comment]
# Walla :sparkles: 

It's available in npm :point_right: http://npm.im/yup-phone
