### ISSUE TITLE
Support multiple regions

### ISSUE THREAD

**Issue by schrapel** [abhisekp/yup-phone#116]
It would be nice if you could accept an array of regions

**Comment by abhisekp** [comment]
This is a nice feature! Will see to it.

**Comment by abhisekp** [comment]
This could be achieved by using multiple `.phone` validation schema.

I'm closing this issue as of now. Please feel free to re-open if you feel like this cannot be achieved otherwise.

**Comment by StackTraceYo** [comment]
Do you have an example of how to do this with multiple .phone validation schemas?
