### ISSUE TITLE
No longer on npm?

### ISSUE THREAD

**Issue by pjaws** [abhisekp/yup-phone#195]
Running `npm install yup-phone` results in a 404

**Comment by dante-blitz** [comment]
same for me

**Comment by nickradford** [comment]
https://github.com/jquense/yup/issues/59#issuecomment-259947426

Here's a quick and easy solution. For a project I'm working on, I just added a `utils/validation.js` file, imported Yup, added this method to it, then exported Yup.

**Comment by httpsOmkar** [comment]
This package is moved to @fyne/yup-phone

**Comment by abhisekp** [comment]
Directly install from github `yarn add abhisekp/yup-phone`

**Comment by abhisekp** [comment]
# Walla :sparkles: 

It's available in npm :point_right: http://npm.im/yup-phone
