### ISSUE TITLE
yarn add yup-phone yarn add v1.22.4 warning ..\package.json: No license field [1/4] Resolving packages... error An unexpected error occurred: "https://registry.yarnpkg.com/yup-phone: Not found".

### ISSUE THREAD

**Issue by hani-q** [abhisekp/yup-phone#219]
Hi,

Unable to add it, 

yarn add yup-phone
yarn add v1.22.4
warning ..\package.json: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/yup-phone: Not found".

**Comment by pushpendra-codemymobile** [comment]
I am getting same error

**Comment by graffme** [comment]
Same here :(

**Comment by Raidouane** [comment]
same error

**Comment by abhisekp** [comment]
Directly install from github `yarn add abhisekp/yup-phone`

**Comment by abhisekp** [comment]
# Walla :sparkles: 

It's available in npm :point_right: http://npm.im/yup-phone
