### ISSUE TITLE
Not installable on windows 10

### ISSUE THREAD

**Issue by matthiasprieth** [abhisekp/yup-phone#247]
![image](https://user-images.githubusercontent.com/4509289/81943098-3ebb1780-95fb-11ea-91a2-778dbe5da668.png)

![image](https://user-images.githubusercontent.com/4509289/81942917-0a475b80-95fb-11ea-8485-a96eb02e841f.png)

**Comment by abhisekp** [comment]
This is because of using `npm` instead of `yarn` for installing.
The change that needs to be done is to move `mpn-on` from dependencies to devDependencies in `package.json`

**Comment by abhisekp** [comment]
This should be fixed. Please confirm.
I'm closing this issue. If this persists, please feel free to reopen.
