### ISSUE TITLE
Add message to validation

### ISSUE THREAD

**Issue by sonnerberg** [abhisekp/yup-phone#265]
Hello,

Thanks a lot for this tool, it seems very useful.

I am new to Yup and I am using it for the first time together with Formik.

I would like to customize the error message that is displayed in my form when an incorrect phone number is entered.

At the moment it says: "[...input] must be a valid phone number."

I am using it like this:
`Yup.string().phone().required()`

When i hover over `required()` I get `required(message?: Yup.TestOptionsMessage<{}, any>): Yup.StringSchema<string>`

I would very much like to add a message to the phone also but here i get: `phone(countryCode?: string, strict?: boolean): Yup.StringSchema<string>`

I am not familiar with TypeScript yet so I don't think I will give a PR a go, but is this something you could implement?

**Comment by abhisekp** [comment]
# Released in npm in `v1.2.0`
