### ISSUE TITLE
TypeError: yup__WEBPACK_IMPORTED_MODULE_4__.string(...).phone is not a function

### ISSUE THREAD

**Issue by kptac** [abhisekp/yup-phone#333]
In registration page, I'm using:

```
import * as Yup from "yup";
import "yup-phone";
```

Then setting RegistrationSchema as follows:

```
const RegistrationSchema = Yup.object().shape({
    first_name: Yup.string()
      .required(),
    last_name: Yup.string()
      .required(),
    email: Yup.string()
      .email("Wrong email format")
      .required(),
    phone: Yup.string()
      .phone()
      .required()
  });
```

But getting this error:

TypeError: yup__WEBPACK_IMPORTED_MODULE_4__.string(...).phone is not a function

I'm working on a new admin theme and fairly new to this. Kindly advice.

Thanks

EDIT: Nevermind, the new version 1.2.4 resolved it 👍

**Comment by Ihtisham-Khattak** [comment]
The same problem affects me as well. Is this problem connected to the **Yup version**?
