### ISSUE TITLE
How to set phone as required phone number in a conditional?

### ISSUE THREAD

**Issue by daniellizik** [abhisekp/yup-phone#550]
- `yup: 0.32.9`
- `yup-phone: 1.2.19`

Given some yup schema, I expect these validations ([codesandbox tests](https://codesandbox.io/s/epic-ishizaka-lmgyl?file=/src/index.test.js))

1. invalid
```
{ email: 'a@a.com', phone: '1' } // valid email, invalid phone
```
2. invalid
```
{ email: 'a', phone: '08012341234' } // invalid email, valid phone (japan)
```
3. validate
```
{ email: '', phone: '08012341234' } // empty email, valid phone (japan)
```
4. validate
```
{ email: 'a@a.com', phone: '' } // valid email, empty phone
```
5. validate
```
{ email: 'a@a.com', phone: '08012341234' } // valid email, valid phone (japan)
```
I've tried these test cases with two different schemas

1
```js
yup.object().shape(
  {
    email: yup
      .string()
      .email()
      .when("phone", {
        is: (val) => !val || val.length < 1,
        then: yup.string().email().required(),
        otherwise: yup.string().email()
      }),
    phone: yup
      .string()
      .phone()
      .when("email", {
        is: (val) => !val || val.length < 1,
        then: yup.string().phone().required(),
        otherwise: yup.string()
      })
  },
  [["email", "phone"]]
);
```
2
```diff
yup.object().shape(
  {
    email: yup
      .string()
      .email()
      .when("phone", {
        is: (val) => !val || val.length < 1,
        then: yup.string().email().required(),
        otherwise: yup.string().email()
      }),
-   phone: yup.string().phone().when("email", {
+   phone: yup.string().when("email", {
      is: (val) => !val || val.length < 1,
      then: yup.string().phone().required(),
      otherwise: yup.string()
    })
  },
  [["email", "phone"]]
);
```
I'm struggling to get all the tests to pass. What is the correct schema to use so that

- valid email + invalid phone = invalidation
- invalid email + valid phone = invalidation
- empty email + valid phone = validation
- valid email + empty phone = validation
- valid email + valid phone = validation

related to https://github.com/jquense/yup/issues/79#issuecomment-699605408

**Comment by abhisekp** [comment]
Only phone number is validated by the extension. And the `required` option feature is added to the implementation.

**Comment by abhisekp** [comment]
Kindly, reach out to me in any of the platforms given below to volunteer for maintaining this repository.
https://about.me/abhisekp
