### ISSUE TITLE
Wrong validation result on some countries

### ISSUE THREAD

**Issue by cesarinmak** [abhisekp/yup-phone#741]
Did not expect alphabets & special characters should be valid for Germany phone number. 

`yup.string().phone('DE', false, 'it's wrong').isValidSync('619490ac8@')`

(also tested the underlying `google-libphonenumber`, consistent results... so I assume it's not our fault on this side 🥲)

---

(p.s. would be nice if the doc could forward us to somewhere to find the list of supported countryCodes)

**Comment by abhisekp** [comment]
I suppose, it need to be reported in the underlying phone validation lib from google.
