### ISSUE TITLE
Showing invalid for some valid area code.

### ISSUE THREAD

**Issue by mashiyatnc** [abhisekp/yup-phone#767]
201 is a valid area code for US. https://www.allareacodes.com/201
The library is not accepting numbers starting with 201.

**Comment by abhisekp** [comment]
How are you passing the area code?
Could you please share the yup-phone code?

**Comment by mashiyatnc** [comment]
@abhisekp Thanks for getting back on this.
This is a problem in the original library as well. https://github.com/google/libphonenumber
We need to send "US" as a default country to resolve the problem, sending blank will raise this issue. 
I think there is nothing Yup-phone can do about it, I am closing it.
